# SEC: Implementation Notes
:authorinitials: AP
:email: andries.spies@gmail.com
:sectnums:
:toc:
:toclevels: 4
:description: SEC tool Implementation notes
:source-highlighter: pygments
:pygments-style: xcode
:highlightjs-theme: xcode

## Traversing JSon Nodes (using Jackson)


### The requirements
A typical configuration document looks something like this:

[source,yaml]
--
server:
  host: localhost
  admin:
    user: admin
    password: "3j75y6btj8pk2jru" # TODO: This must be encrypted <1>
  adapters:
    - protocol: http
      port: 8080
    - protocol: https
      port: 8774
      keystore:
        path: keystore.jks
        format: JKS
        password: "w6niz798tqdhqfvu" # TODO: This must be encrypted <1>
--
<1> These need to be encrypted!

Encryption governed via the key being used, and a path to value to be encrypted. In the above example, the following paths should be specified:

[source,text]
--
server.admin.password
server.admin.user
server.adapters.*.keystore.password
--

### The Algorithm

Say we start of our sample yaml. The first node we get is an `ObjectNode` with the following direct children: `host`, `admin` and `adapters`.




