---
server:
  host: localhost
  admin:
    user: admin
    password: "3j75y6btj8pk2jru" # TODO: This must be encrypted
  adapters:
    - protocol: http
      port: 8080
    - protocol: https
      port: 8774
      keystore:
        path: keystore.jks
        format: JKS
        password: "w6niz798tqdhqfvu" # TODO: This must be encrypted
